# Import properties for LambdaFunction (AWS::Lambda::Function)
# 
#     FunctionName: signup
# 
# Import properties for S3Bucket (AWS::S3::Bucket)
# 
#     BucketName: 315209879108-welcome
# 
# Import properties for DynamoDBTable (AWS::DynamoDB::Table)
# 
#     TableName: customer_details
# 
# Import properties for DynamoDBTable2 (AWS::DynamoDB::Table)
# 
#     TableName: waiting_list
# 
# Import properties for ApiGatewayRestApi (AWS::ApiGateway::RestApi)
# 
#     RestApiId: 0gqdumjyl2
# 
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    LambdaFunction:
        DeletionPolicy: "Retain"
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "signup"
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "prod-04-2014-tasks"
                S3Key: !Sub "/snapshots/${AWS::AccountId}/signup-a611dc86-3515-4fcb-b158-dd9d67c0d0a1"
                S3ObjectVersion: "nBvAJlQjJblaeQkQHPcKwhvQVaRfva2r"
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/signup-role-2rnu0euj"
            Runtime: "python3.9"
            Timeout: 3
            TracingConfig: 
                Mode: "PassThrough"

    S3Bucket:
        DeletionPolicy: "Retain"
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Sub "${AWS::AccountId}-welcome"
            CorsConfiguration: 
                CorsRules: 
                  - 
                    AllowedHeaders: 
                      - "*"
                    AllowedMethods: 
                      - "PUT"
                      - "POST"
                      - "DELETE"
                    AllowedOrigins: 
                      - "*"
                  - 
                    AllowedHeaders: 
                      - "*"
                    AllowedMethods: 
                      - "PUT"
                      - "POST"
                      - "DELETE"
                    AllowedOrigins: 
                      - "*"
                  - 
                    AllowedMethods: 
                      - "GET"
                    AllowedOrigins: 
                      - "*"
            WebsiteConfiguration: 
                IndexDocument: "login-page.html"
                ErrorDocument: "login-page.html"

    DynamoDBTable:
        DeletionPolicy: "Retain"
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "email"
                AttributeType: "S"
            TableName: "customer_details"
            KeySchema: 
              - 
                AttributeName: "email"
                KeyType: "HASH"
            ProvisionedThroughput: 
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            TimeToLiveSpecification: 
                Enabled: false

    DynamoDBTable2:
        DeletionPolicy: "Retain"
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "id"
                AttributeType: "S"
            TableName: "waiting_list"
            KeySchema: 
              - 
                AttributeName: "id"
                KeyType: "HASH"
            ProvisionedThroughput: 
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
            TimeToLiveSpecification: 
                Enabled: false

    ApiGatewayRestApi:
        DeletionPolicy: "Retain"
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Name: "api1"
            ApiKeySourceType: "HEADER"
            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"

